<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="container">
	 

<main role="main" class="container">
  <div class="jumbotron">
    <h1>404 - Pagina não encontrada</h1> 
    
  </div>
  <div class="col-md-12">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non praesentium facere sint sequi laudantium nesciunt quas repudiandae corporis. Pariatur nesciunt nemo voluptate possimus, voluptatibus quod ducimus sit amet veritatis aut.</p>
    </div>
    
</main>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>