<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="container">
	

<main role="main" class="container">
  <div class="jumbotron">
    <h1>Info Enter</h1>
    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum eos cupiditate vel nam possimus modi nostrum hic amet praesentium mollitia, pariatur officia soluta quo sed, inventore, fugit delectus incidunt odit!</p>
    <a class="btn btn-lg btn-primary" href="#" role="button">View navbar docs &raquo;</a>
  </div>
</main>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>